import type { NextPage } from "next";
import Head from "next/head";
import Image from "next/image";
import Hero from "../components/Hero";
import Navbar from "../components/Navbar";
import ProjectsPage from "../components/ProjectsPage";
import Footer from "../components/Footer";
import { sanityClient } from "../lib/sanity.server";

const Home: NextPage = ({ projects }) => {
  console.log(projects);
  return (
    <div>
      <Head>
        <title>Wyatt Connolly</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Navbar />
      <main className="bg-[#18181B]">
        <Hero />
        <ProjectsPage projects={projects} />
      </main>
      <Footer />
    </div>
  );
};

export async function getStaticProps() {
  const projects = await sanityClient.fetch(`*[_type == "project"]`);

  return {
    props: {
      projects,
    },
  };
}
export default Home;
